# Generated by Django 6.0.3 on 2026-05-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cyberclub_appointment_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time', '-created_at']},
        ),
    ]
