# Generated by Django 6.0.3 on 2026-06-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_admin_ban_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('zone', models.CharField(blank=True, default='all', max_length=30, verbose_name='Зона каталога')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Время на странице (сек)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало просмотра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия каталога',
                'verbose_name_plural': 'Сессии каталога',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('tariff', models.CharField(max_length=120, verbose_name='Тариф')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр тарифа',
                'verbose_name_plural': 'Просмотры тарифов',
                'ordering': ['-created_at'],
            },
        ),
    ]
